# pipeline_registry.py - Central metadata for all ESKAPE + E. coli pipelines
# Updated with new output structures, flags, and module descriptions
# author: Brown Beckley <brownbeckley94@gmail.com>
# 2026-08-03

PIPELINE_REGISTRY = {
    'staphscope': {
        'name': 'Staphylococcus aureus',
        'slug': 'staphscope',
        'color': '#DC143C',          # Crimson
        'description': 'A species-optimized computational pipeline for rapid and accessible Staphylococcus aureus genotyping and surveillance.',
        'version': '1.3.2',
        'github': 'https://github.com/bbeckley-hub/staphscope-typing-tool',
        'publication': 'Beckley B, Amarh V. StaphScope: a species-optimized computational pipeline for rapid and accessible Staphylococcus aureus genotyping and surveillance. BMC Genomics. 2026;27:261. doi:10.1186/s12864-026-12609-x',
        'module_descriptions': {
            'fasta_qc': 'Quality control and assembly statistics for your input genomes. Checks N50, GC%, and sequence counts.',
            'mlst': 'Multi-Locus Sequence Typing – determines the sequence type (ST) using seven housekeeping genes.',
            'spa': 'spa typing – characterises the polymorphic X region of the protein A gene for epidemiological tracking.',
            'sccmec': 'SCCmec typing – identifies the methicillin resistance cassette type (I‑XIII) and subtype.',
            'agr': 'agr typing – determines the accessory gene regulator group (I‑IV) for virulence profiling.',
            'amr': 'AMR profiling – detects acquired resistance genes and point mutations using AMRFinderPlus.',
            'abricate': 'ABRicate – screens against 10+ databases for resistance, virulence, plasmid, and biocide genes.',
            'lineage': 'Lineage reference – generates a comprehensive reference database for S. aureus lineages.',
            'comprehensive': 'Comprehensive report – combines MLST, spa, SCCmec, and agr into a single summary.',
            'sample_centric': 'Sample‑centric report – interactive, isolate‑focused HTML report with typing badges.',
            'visualization': 'Visualization – generates publication‑ready charts and dashboards.',
        },
        'skip_flags': ['fasta_qc', 'mlst', 'spa', 'sccmec', 'agr', 'amr', 'abricate', 'lineage', 'comprehensive', 'sample_centric', 'visualization'],
        'skip_flag_map': {
            'fasta_qc': '--skip-fasta-qc',
            'mlst': '--skip-mlst',
            'spa': '--skip-spa',
            'sccmec': '--skip-sccmec',
            'agr': '--skip-agr',
            'amr': '--skip-amr',
            'abricate': '--skip-abricate',
            'lineage': '--skip-lineage',
            'comprehensive': '--skip-comprehensive',
            'sample_centric': '--skip-sample-centric',
            'visualization': '--skip-visualization',
        },
        'params': {
            'amr_min_identity': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.95},
            'amr_min_coverage': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.85},
            'skip_amr_mutations': {'type': 'bool', 'default': False},
            'abricate_minid': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
            'abricate_mincov': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
        },
        'quote': 'The important thing in science is not so much to obtain new facts as to discover new ways of thinking about them. — William Lawrence Bragg',
        'modules': [
            {'name': 'Gene-Centric Ultimate Report', 'path': 'Staphscope_final_report/STAPHSCOPE_ULTIMATE_GENE_CENTRIC_REPORTS/staphscope_ultimate_gene_centric_report.html'},
            {'name': 'Sample-Centric Ultimate Report', 'path': 'Staphscope_final_report/STAPHSCOPE_ULTIMATE_SAMPLE_CENTRIC_REPORTS/staphscope_ultimate_sample_centric_report.html'},
            {'name': 'Comprehensive Summary Report', 'path': 'Staphscope_final_report/staphscope_comprehensive_report.html'},
            {'name': 'FASTA QC Summary', 'path': 'fasta_qc_results/FASTA_QC_summary.html'},
            {'name': 'MLST Summary', 'path': 'mlst_results/mlst_summary.html'},
            {'name': 'spa Typing Summary', 'path': 'spa_results/spa_summary.html'},
            {'name': 'SCCmec Summary', 'path': 'sccmec_results/staphscope_summary.html'},
            {'name': 'agr Typing Summary', 'path': 'agr_results/agr_summary.html'},
            {'name': 'AMR Summary', 'path': 'staph_amrfinder_results/staph_amrfinder_summary_report.html'},
            {'name': 'Lineage Reference', 'path': 'lineage_results/staphscope_lineage_reference.html'},
            {'name': 'CARD Summary', 'path': 'abricate_results/staph_card_summary_report.html'},
            {'name': 'ResFinder Summary', 'path': 'abricate_results/staph_resfinder_summary_report.html'},
            {'name': 'VFDB Summary', 'path': 'abricate_results/staph_vfdb_summary_report.html'},
            {'name': 'PlasmidFinder Summary', 'path': 'abricate_results/staph_plasmidfinder_summary_report.html'},
        ]
    },
    'acinetoscope': {
        'name': 'Acinetobacter baumannii',
        'slug': 'acinetoscope',
        'color': '#008080',          # Teal
        'description': 'A species-specific computational pipeline for rapid, comprehensive Acinetobacter baumannii outbreak investigation and resistance gene tracking.',
        'version': '1.3.1',
        'github': 'https://github.com/bbeckley-hub/acinetoscope',
        'publication': 'Manuscript in preparation',
        'module_descriptions': {
            'qc': 'Quality control and assembly statistics for your input genomes.',
            'mlst': 'Multi-Locus Sequence Typing – determines the sequence type (ST) using Pasteur and/or Oxford schemes.',
            'kaptive': 'Kaptive – identifies capsular (K) and lipooligosaccharide (O) loci for high-resolution typing.',
            'amr': 'AMR profiling – detects acquired resistance genes and point mutations using AMRFinderPlus.',
            'abricate': 'ABRicate – screens against 10+ databases for resistance, virulence, plasmid, and biocide genes.',
            'plasmid': 'Plasmid typing – identifies plasmid replicons using APT (Acinetobacter Plasmid Typing).',
            'gene_centric': 'Gene‑centric report – focuses on gene distribution and co-occurrence patterns.',
            'sample_centric': 'Sample‑centric report – interactive, isolate‑focused HTML report.',
        },
        'skip_flags': ['qc', 'mlst', 'kaptive', 'amr', 'abricate', 'plasmid', 'gene_centric', 'sample_centric'],
        'skip_flag_map': {
            'qc': '--skip-qc',
            'mlst': '--skip-mlst',
            'kaptive': '--skip-kaptive',
            'amr': '--skip-amr',
            'abricate': '--skip-abricate',
            'plasmid': '--skip-plasmid',
            'gene_centric': '--skip-gene-centric',
            'sample_centric': '--skip-sample-centric',
        },
        'params': {
            'mlst_scheme': {'type': 'choice', 'choices': ['pasteur', 'oxford', 'both'], 'default': 'both'},
            'amr_min_identity': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.95},
            'amr_min_coverage': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.85},
            'skip_amr_mutations': {'type': 'bool', 'default': False},
            'abricate_min_identity': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
            'abricate_min_coverage': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
        },
        'quote': 'The microbe is nothing; the terrain is everything. — Louis Pasteur',
        'modules': [
            {'name': 'Gene-Centric Ultimate Report', 'path': 'AcinetoScope_final_reports/GENIUS_ACINETOBACTER_GENE_CENTRIC_REPORTS/genius_acinetobacter_ultimate_gene_centric_report.html'},
            {'name': 'Sample-Centric Ultimate Report', 'path': 'AcinetoScope_final_reports/GENIUS_ACINETOBACTER_SAMPLE_CENTRIC_REPORTS/genius_acinetobacter_sample_centric_report.html'},
            {'name': 'FASTA QC Summary', 'path': 'fasta_qc_results/FASTA_QC_summary.html'},
            {'name': 'MLST Summary (Pasteur)', 'path': 'PASTEUR_MLST/pasteur_mlst_summary.html'},
            {'name': 'MLST Summary (Oxford)', 'path': 'OXFORD_MLST/oxford_mlst_summary.html'},
            {'name': 'Kaptive Summary', 'path': 'kaptive_results/Kaptive_summary.html'},
            {'name': 'AMR Summary', 'path': 'acineto_amrfinder_results/acineto_amrfinder_summary_report.html'},
            {'name': 'Plasmid Summary', 'path': 'acineto_plasmid_results/plasmid_summary_report.html'},
            {'name': 'CARD Summary', 'path': 'acineto_abricate_results/acineto_card_summary_report.html'},
            {'name': 'ResFinder Summary', 'path': 'acineto_abricate_results/acineto_resfinder_summary_report.html'},
            {'name': 'VFDB Summary', 'path': 'acineto_abricate_results/acineto_vfdb_summary_report.html'},
        ]
    },
    'ecolityper': {
        'name': 'Escherichia coli',
        'slug': 'ecolityper',
        'color': '#4169E1',          # Royal Blue
        'description': 'A species-optimized computational pipeline for comprehensive genotyping and surveillance of Escherichia coli.',
        'version': '1.3.0',
        'github': 'https://github.com/bbeckley-hub/EcoliTyper',
        'publication': 'Beckley, B., Amarh, V. EcoliTyper: a species-optimized computational pipeline for comprehensive genotyping and surveillance of Escherichia coli. BMC Bioinformatics (2026). https://doi.org/10.1186/s12859-026-06529-6',
        'module_descriptions': {
            'fasta_qc': 'Quality control and assembly statistics for your input genomes.',
            'amrfinder': 'AMR profiling – detects acquired resistance genes and point mutations using AMRFinderPlus.',
            'abricate': 'ABRicate – screens against 10+ databases for resistance, virulence, plasmid, and biocide genes.',
            'mlst': 'Multi-Locus Sequence Typing – determines the sequence type (ST) using seven housekeeping genes.',
            'serotyping': 'Serotyping – determines O and H antigens for E. coli serotype identification.',
            'chtyper': 'CH typing – high-resolution typing based on fumC and fimH alleles.',
            'phylogrouping': 'Phylogrouping – assigns E. coli to one of eight phylogroups (A, B1, B2, C, D, E, F, G).',
            'lineage': 'Lineage reference – generates a comprehensive reference database for E. coli lineages.',
            'summary': 'Gene‑centric report – focuses on gene distribution and co-occurrence patterns.',
            'samplecentric': 'Sample‑centric report – interactive, isolate‑focused HTML report.',
            'visualization': 'Visualization – generates publication‑ready charts and dashboards.',
        },
        'skip_flags': ['fasta_qc', 'amrfinder', 'abricate', 'mlst', 'serotyping', 'chtyper', 'phylogrouping', 'lineage', 'summary', 'samplecentric', 'visualization'],
        'skip_flag_map': {
            'fasta_qc': '--skip-fasta-qc',
            'amrfinder': '--skip-amrfinder',
            'abricate': '--skip-abricate',
            'mlst': '--skip-mlst',
            'serotyping': '--skip-serotyping',
            'chtyper': '--skip-chtyper',
            'phylogrouping': '--skip-phylogrouping',
            'lineage': '--skip-lineage',
            'summary': '--skip-summary',
            'samplecentric': '--skip-samplecentric',
            'visualization': '--skip-visualization',
        },
        'params': {
            'amr_min_identity': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.95},
            'amr_min_coverage': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.85},
            'skip_amr_mutations': {'type': 'bool', 'default': False},
            'abricate_minid': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
            'abricate_mincov': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
        },
        'quote': 'Science is organised knowledge. — Herbert Spencer',
        'modules': [
            {'name': 'Gene-Centric Ultimate Report', 'path': 'GENIUS_ECOLI_ULTIMATE_GENE_CENTRIC_REPORTS/genius_ecoli_ultimate_gene_centric_report.html'},
            {'name': 'Sample-Centric Ultimate Report', 'path': 'GENIUS_ECOLI_ULTIMATE_SAMPLE_CENTRIC_REPORTS/genius_ecoli_ultimate_sample_centric_report.html'},
            {'name': 'FASTA QC Summary', 'path': 'fasta_qc_results/FASTA_QC_summary.html'},
            {'name': 'MLST Summary', 'path': 'mlst_results/mlst_summary.html'},
            {'name': 'Serotyping Summary', 'path': 'serotyping_results/serotype_analysis_report.html'},
            {'name': 'CH Typing Summary', 'path': 'chtyper_results/chtyper_results.html'},
            {'name': 'Phylogrouping Summary', 'path': 'phylogrouping_results/phylogrouping_results.html'},
            {'name': 'CARD Summary', 'path': 'abricate_results/ecoli_card_summary_report.html'},
            {'name': 'ResFinder Summary', 'path': 'abricate_results/ecoli_resfinder_summary_report.html'},
            {'name': 'VFDB Summary', 'path': 'abricate_results/ecoli_vfdb_summary_report.html'},
            {'name': 'PlasmidFinder Summary', 'path': 'abricate_results/ecoli_plasmidfinder_summary_report.html'},
            {'name': 'AMR Summary', 'path': 'amrfinder_results/ecoli_amrfinder_summary_report.html'},
            {'name': 'Lineage Reference', 'path': 'lineage_results/ecoli_comprehensive_reference.html'},
        ]
    },
    'kleboscope': {
        'name': 'Klebsiella pneumoniae',
        'slug': 'kleboscope',
        'color': '#6A0DAD',          # Purple
        'description': 'A gene‑centric, species‑optimized computational pipeline for comprehensive Klebsiella pneumoniae genomic surveillance.',
        'version': '1.2.0',
        'github': 'https://github.com/bbeckley-hub/Kleboscope',
        'publication': 'Brown Beckley. Kleboscope: A gene‑centric, species‑optimized computational pipeline for comprehensive Klebsiella pneumoniae genomic surveillance. Github: https://github.com/bbeckley-hub/Kleboscope',
        'module_descriptions': {
            'qc': 'Quality control and assembly statistics for your input genomes.',
            'mlst': 'Multi-Locus Sequence Typing – determines the sequence type (ST) using seven housekeeping genes.',
            'kaptive': 'Kaptive – identifies capsular (K) and lipooligosaccharide (O) loci for high-resolution typing.',
            'abricate': 'ABRicate – screens against 10+ databases for resistance, virulence, plasmid, and biocide genes.',
            'amr': 'AMR profiling – detects acquired resistance genes and point mutations using AMRFinderPlus.',
            'summary': 'Gene‑centric report – focuses on gene distribution and co-occurrence patterns.',
            'sample_centric': 'Sample‑centric report – interactive, isolate‑focused HTML report.',
        },
        'skip_flags': ['qc', 'mlst', 'kaptive', 'abricate', 'amr', 'summary', 'sample_centric'],
        'skip_flag_map': {
            'qc': '--skip-qc',
            'mlst': '--skip-mlst',
            'kaptive': '--skip-kaptive',
            'abricate': '--skip-abricate',
            'amr': '--skip-amr',
            'summary': '--skip-summary',
            'sample_centric': '--skip-sample-centric',
        },
        'params': {
            'amr_min_identity': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.95},
            'amr_min_coverage': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.85},
            'skip_amr_mutations': {'type': 'bool', 'default': False},
            'abricate_min_id': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
            'abricate_min_cov': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
        },
        'quote': 'Resistance is not futile. — Antibiotic Researcher',
        'modules': [
            {'name': 'Gene-Centric Ultimate Report', 'path': 'KLEBOSCOPE_ULTIMATE_GENE_CENTRIC_REPORTS/kleboscope_ultimate_gene_centric_report.html'},
            {'name': 'Sample-Centric Ultimate Report', 'path': 'KLEBOSCOPE_ULTIMATE_SAMPLE_CENTRIC_REPORTS/kleboscope_ultimate_sample_centric_report.html'},
            {'name': 'FASTA QC Summary', 'path': 'fasta_qc_results/klebo_fasta_qc_summary.html'},
            {'name': 'MLST Summary', 'path': 'mlst_results/mlst_summary.html'},
            {'name': 'Kaptive Summary', 'path': 'kaptive_results/klebo_kaptive_summary.html'},
            {'name': 'AMR Summary', 'path': 'klebo_amrfinder_results/klebo_amrfinder_summary_report.html'},
            {'name': 'CARD Summary', 'path': 'abricate_results/klebo_card_summary_report.html'},
            {'name': 'ResFinder Summary', 'path': 'abricate_results/klebo_resfinder_summary_report.html'},
            {'name': 'VFDB Summary', 'path': 'abricate_results/klebo_vfdb_summary_report.html'},
            {'name': 'PlasmidFinder Summary', 'path': 'abricate_results/klebo_plasmidfinder_summary_report.html'},
        ]
    },
    'pseudoscope': {
        'name': 'Pseudomonas aeruginosa',
        'slug': 'pseudoscope',
        'color': '#228B22',          # Forest Green
        'description': 'A species‑specific bioinformatics suite for rapid and accessible Pseudomonas aeruginosa genomic surveillance.',
        'version': '1.2.0',
        'github': 'https://github.com/bbeckley-hub/pseudoscope',
        'publication': 'Brown Beckley. PseudoScope: A species‑specific bioinformatics suite for rapid and accessible Pseudomonas aeruginosa genomic surveillance. Github: https://github.com/bbeckley-hub/pseudoscope.',
        'module_descriptions': {
            'qc': 'Quality control and assembly statistics for your input genomes.',
            'mlst': 'Multi-Locus Sequence Typing – determines the sequence type (ST) using seven housekeeping genes.',
            'past': 'PAST serotyping – determines the O-antigen serotype for epidemiological tracking.',
            'abricate': 'ABRicate – screens against 10+ databases for resistance, virulence, plasmid, and biocide genes.',
            'amr': 'AMR profiling – detects acquired resistance genes and point mutations using AMRFinderPlus.',
            'summary': 'Gene‑centric report – focuses on gene distribution and co-occurrence patterns.',
            'sample_centric': 'Sample‑centric report – interactive, isolate‑focused HTML report.',
            'viz': 'Visualisation – generates publication‑ready charts and dashboards.',
        },
        'skip_flags': ['qc', 'mlst', 'past', 'abricate', 'amr', 'summary', 'sample_centric', 'viz'],
        'skip_flag_map': {
            'qc': '--skip-qc',
            'mlst': '--skip-mlst',
            'past': '--skip-past',
            'abricate': '--skip-abricate',
            'amr': '--skip-amr',
            'summary': '--skip-summary',
            'sample_centric': '--skip-sample-centric',
            'viz': '--skip-viz',
        },
        'params': {
            'past_min_pident': {'type': 'int', 'min': 0, 'max': 100, 'default': 95},
            'past_min_coverage': {'type': 'int', 'min': 0, 'max': 100, 'default': 95},
            'abricate_minid': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
            'abricate_mincov': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
            'amr_min_identity': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.95},
            'amr_min_coverage': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.85},
            'amr_skip_mutations': {'type': 'bool', 'default': False},
        },
        'quote': 'Science knows no country, because knowledge belongs to humanity. — Louis Pasteur',
        'modules': [
            {'name': 'Gene-Centric Ultimate Report', 'path': 'GENIUS_PSEUDOMONAS_ULTIMATE_GENE_CENTRIC_REPORTS/genius_pseudomonas_ultimate_gene_centric_report.html'},
            {'name': 'Sample-Centric Ultimate Report', 'path': 'GENIUS_PSEUDOMONAS_SAMPLE_CENTRIC_REPORTS/genius_pseudomonas_sample_centric_report.html'},
            {'name': 'FASTA QC Summary', 'path': 'fasta_qc_results/PseudoScope_FASTA_QC_summary.html'},
            {'name': 'MLST Summary', 'path': 'mlst_results/mlst_summary.html'},
            {'name': 'PAST Serotyping Summary', 'path': 'past_results/past_summary.html'},
            {'name': 'AMR Summary', 'path': 'pseudo_amrfinder_results/pseudo_amrfinder_summary_report.html'},
            {'name': 'CARD Summary', 'path': 'pseudo_abricate_results/pseudo_card_summary_report.html'},
            {'name': 'ResFinder Summary', 'path': 'pseudo_abricate_results/pseudo_resfinder_summary_report.html'},
            {'name': 'VFDB Summary', 'path': 'pseudo_abricate_results/pseudo_vfdb_summary_report.html'},
            {'name': 'Visual Dashboard', 'path': 'GENIUS_PSEUDOMONAS_VISUAL_DASHBOARD/genius_pseudomonas_visual_dashboard.html'},
        ]
    },
    'enteromark': {
        'name': 'Enterococcus faecium',
        'slug': 'enteromark',
        'color': '#FF8C00',          # Orange
        'description': 'A species-optimized computational pipeline for rapid, accessible Enterococcus faecium genotyping and surveillance.',
        'version': '1.0.0',
        'github': 'https://github.com/bbeckley-hub/EnteroMark',
        'publication': 'Manuscript in preparation',
        'module_descriptions': {
            'qc': 'Quality control and assembly statistics for your input genomes.',
            'mlst': 'Multi-Locus Sequence Typing – determines the sequence type (ST) using seven housekeeping genes.',
            'abricate': 'ABRicate – screens against 10+ databases for resistance, virulence, plasmid, and biocide genes.',
            'amr': 'AMR profiling – detects acquired resistance genes and point mutations using AMRFinderPlus.',
            'summary': 'Gene‑centric report – focuses on gene distribution and co-occurrence patterns.',
        },
        'skip_flags': ['qc', 'mlst', 'abricate', 'amr', 'summary'],
        'skip_flag_map': {
            'qc': '--skip-qc',
            'mlst': '--skip-mlst',
            'abricate': '--skip-abricate',
            'amr': '--skip-amr',
            'summary': '--skip-summary',
        },
        'params': {},
        'quote': 'Every microbe has its own story. — Anonymous',
        'modules': [
            {'name': 'Ultimate Report', 'path': 'ENTEROMARK_ULTIMATE_REPORTS/enteromark_ultimate_report.html'},
            {'name': 'FASTA QC Summary', 'path': 'fasta_qc_results/enteromark_fasta_qc_summary.html'},
            {'name': 'MLST Summary', 'path': 'mlst_results/mlst_summary.html'},
            {'name': 'CARD Summary', 'path': 'enteromark_abricate_results/enteromark_card_summary_report.html'},
            {'name': 'ResFinder Summary', 'path': 'enteromark_abricate_results/enteromark_resfinder_summary_report.html'},
            {'name': 'VFDB Summary', 'path': 'enteromark_abricate_results/enteromark_vfdb_summary_report.html'},
            {'name': 'PlasmidFinder Summary', 'path': 'enteromark_abricate_results/enteromark_plasmidfinder_summary_report.html'},
            {'name': 'AMR Summary', 'path': 'enteromark_amr_results/enteromark_amrfinder_summary_report.html'},
        ]
    },
    'enteroscope': {
        'name': 'Enterobacter cloacae complex',
        'slug': 'enteroscope',
        'color': '#708090',          # Slate Gray
        'description': 'A Tailored Computational Workflow Enabling Rapid, User-Friendly Genotyping and Epidemiological Surveillance of the Enterobacter cloacae Complex.',
        'version': '1.1.0',
        'github': 'https://github.com/bbeckley-hub/enteroscope',
        'publication': 'Brown Beckley. EnteroScope: A Tailored Computational Workflow Enabling Rapid, User-Friendly Genotyping and Epidemiological Surveillance of the Enterobacter cloacae Complex. Github: https://github.com/bbeckley-hub/enteroscope',
        'module_descriptions': {
            'qc': 'Quality control and assembly statistics for your input genomes.',
            'mlst': 'Multi-Locus Sequence Typing – determines the sequence type (ST) using seven housekeeping genes.',
            'abricate': 'ABRicate – screens against 10+ databases for resistance, virulence, plasmid, and biocide genes.',
            'amr': 'AMR profiling – detects acquired resistance genes and point mutations using AMRFinderPlus.',
            'summary': 'Gene‑centric report – focuses on gene distribution and co-occurrence patterns.',
        },
        'skip_flags': ['qc', 'mlst', 'abricate', 'amr', 'summary'],
        'skip_flag_map': {
            'qc': '--skip-qc',
            'mlst': '--skip-mlst',
            'abricate': '--skip-abricate',
            'amr': '--skip-amr',
            'summary': '--skip-summary',
        },
        'params': {
            'amr_min_identity': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.95},
            'amr_min_coverage': {'type': 'float', 'min': 0.0, 'max': 1.0, 'default': 0.85},
            'skip_amr_mutations': {'type': 'bool', 'default': False},
            'abricate_min_identity': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
            'abricate_min_coverage': {'type': 'int', 'min': 0, 'max': 100, 'default': 80},
        },
        'quote': 'Genomics is a lens on biology. — Eric Lander',
        'modules': [
            {'name': 'Ultimate Report', 'path': 'ENTERO_ULTIMATE_REPORTS/enteroscope_ultimate_report.html'},
            {'name': 'FASTA QC Summary', 'path': 'fasta_qc_results/FASTA_QC_summary.html'},
            {'name': 'MLST Summary', 'path': 'mlst_results/mlst_summary.html'},
            {'name': 'CARD Summary', 'path': 'enteroscope_abricate_results/enteroscope_card_summary_report.html'},
            {'name': 'ResFinder Summary', 'path': 'enteroscope_abricate_results/enteroscope_resfinder_summary_report.html'},
            {'name': 'VFDB Summary', 'path': 'enteroscope_abricate_results/enteroscope_vfdb_summary_report.html'},
            {'name': 'PlasmidFinder Summary', 'path': 'enteroscope_abricate_results/enteroscope_plasmidfinder_summary_report.html'},
            {'name': 'AMR Summary', 'path': 'enteroscope_amrfinder_results/enteroscope_amrfinder_summary_report.html'},
        ]
    }
}

# Order for landing page (ESKAPE + E. coli)
LANDING_ORDER = ['enteromark', 'staphscope', 'kleboscope', 'acinetoscope', 'pseudoscope', 'enteroscope', 'ecolityper']